/**
 * Utilities for exporting an explanation.
 * Markdown is generated inline (no deps). PDF uses jsPDF on the client side.
 */

import jsPDF from 'jspdf';
import type { ExplanationResponse } from './types';

export function explanationToMarkdown(
  code: string,
  language: string,
  exp: ExplanationResponse,
): string {
  const lines: string[] = [];
  lines.push(`# CodeExplain — ${exp.overview}`);
  lines.push('');
  lines.push(`> Language: **${exp.detected_language || language}** · Model: **${exp.model_used}** (${exp.provider_used})`);
  lines.push('');
  lines.push('## Submitted code');
  lines.push('```' + (exp.detected_language || language));
  lines.push(code);
  lines.push('```');
  lines.push('');
  lines.push('## Plain-English explanation');
  lines.push(exp.plain_english_explanation);
  lines.push('');
  lines.push('## Time complexity');
  lines.push(`**${exp.time_complexity.big_o}** — ${exp.time_complexity.reasoning}`);
  lines.push('');
  lines.push('## Space complexity');
  lines.push(`**${exp.space_complexity.big_o}** — ${exp.space_complexity.reasoning}`);
  lines.push('');
  lines.push('## Line-by-line walkthrough');
  exp.line_by_line.forEach((l) => {
    lines.push(`### Line ${l.line_range}`);
    lines.push('```');
    lines.push(l.code_snippet);
    lines.push('```');
    lines.push(l.explanation);
    lines.push('');
  });
  lines.push('## Suggested improvements');
  exp.improvements.forEach((imp) => {
    lines.push(`### ${imp.title} _(${imp.category})_`);
    lines.push(imp.detail);
    lines.push('');
  });
  lines.push('---');
  lines.push('_Generated by CodeExplain._');
  return lines.join('\n');
}

export function downloadText(filename: string, content: string, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/**
 * Render the explanation as a paginated, wrapped-text PDF using jsPDF text
 * primitives. We deliberately avoid html2canvas here because the dark UI
 * doesn't rasterise cleanly — plain text prints far more legibly.
 */
export function explanationToPdf(
  code: string,
  language: string,
  exp: ExplanationResponse,
): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const write = (text: string, opts: { size?: number; style?: 'normal' | 'bold'; mono?: boolean } = {}) => {
    const size = opts.size ?? 11;
    doc.setFont(opts.mono ? 'courier' : 'helvetica', opts.style ?? 'normal');
    doc.setFontSize(size);
    const wrapped = doc.splitTextToSize(text, maxWidth);
    for (const line of wrapped) {
      if (y > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += size * 1.35;
    }
    y += 4;
  };

  write('CodeExplain', { size: 20, style: 'bold' });
  write(exp.overview, { size: 12 });
  write(
    `Language: ${exp.detected_language || language}   ·   Model: ${exp.model_used} (${exp.provider_used})`,
    { size: 10 },
  );

  write('Submitted code', { size: 13, style: 'bold' });
  write(code, { size: 9.5, mono: true });

  write('Plain-English explanation', { size: 13, style: 'bold' });
  write(exp.plain_english_explanation);

  write(`Time complexity — ${exp.time_complexity.big_o}`, { size: 13, style: 'bold' });
  write(exp.time_complexity.reasoning);

  write(`Space complexity — ${exp.space_complexity.big_o}`, { size: 13, style: 'bold' });
  write(exp.space_complexity.reasoning);

  write('Line-by-line walkthrough', { size: 13, style: 'bold' });
  exp.line_by_line.forEach((l) => {
    write(`Line ${l.line_range}`, { size: 11, style: 'bold' });
    write(l.code_snippet, { size: 9.5, mono: true });
    write(l.explanation);
  });

  write('Suggested improvements', { size: 13, style: 'bold' });
  exp.improvements.forEach((imp) => {
    write(`${imp.title}  (${imp.category})`, { size: 11, style: 'bold' });
    write(imp.detail);
  });

  doc.save('codeexplain.pdf');
}
